# Generated by Django 3.1.3 on 2020-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfoliomain', '0005_auto_20201210_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
